export const genreOptions = [
  { en: "Action", bg: "Екшън" },
  { en: "Adventure", bg: "Приключенски" },
  { en: "Animation", bg: "Анимация" },
  { en: "Biography", bg: "Биография" },
  { en: "Comedy", bg: "Комедия" },
  { en: "Crime", bg: "Криминален" },
  { en: "Documentary", bg: "Документален" },
  { en: "Drama", bg: "Драма" },
  { en: "Family", bg: "Семейни" },
  { en: "Fantasy", bg: "Фентъзи" },
  { en: "Film-Noir", bg: "Филм-ноар" },
  { en: "History", bg: "Исторически" },
  { en: "Horror", bg: "Ужаси" },
  { en: "Music", bg: "Музика" },
  { en: "Musical", bg: "Мюзикъл" },
  { en: "Mystery", bg: "Мистерия" },
  { en: "Romance", bg: "Романтичен" },
  { en: "Sci-Fi", bg: "Научна фантастика" },
  { en: "Sport", bg: "Спортен" },
  { en: "Thriller", bg: "Трилър" },
  { en: "War", bg: "Военен" },
  { en: "Western", bg: "Уестърн" }
];
